const user = require('./user');
const admin = require('./admin');
const vote = require('./vote');
const item = require('./vote.item');
const record = require('./vote.record');
const whitelist = require('./whitelist');
const service = require('./service');
const home = require('./home');
module.exports = { user, admin, vote, item, record, whitelist, service, home, };